backend:
  - src/*
  - tests/*

ci_cd:
  - .github/workflows/deploy.yml

dependencies:
  - poetry.lock
  - requirements.txt

auth:
  - src/security.py
  - src/routers/auth.py
  - src/routers/gmail_auth.py

# any file in static or templates
# but if the only change is in base.html, then no label
frontend:
  - any: ["static/*", "templates/*"]
    all: ["!templates/base.html"]

database:
  - src/models.py
