backend:
- src/*
- tests/*

cd:
- .github/workflows/deploy.yml
- docker/*
- requirements.txt

ci:
- .github/workflows/test.yml

dependencies:
- Pipfile
- requirements.txt

frontend:
- static/*
- templates/*
