backend:
- src/*
- tests/*

cd:
- .github/workflows/deploy.yml
- docker/*
- requirements.txt

ci:
- .github/workflows/test.yml

dependencies:
- poetry.lock
- requirements.txt

# any file in static or templates
# but if the only change is in base.html, then no label
frontend:
- any: ['static/*', 'templates/*']
  all: ['!templates/base.html']