# rest-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: nba-elt-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nba-elt-rest-api
  template:
    metadata:
      labels:
        app: nba-elt-rest-api
    spec:
      containers:
      - name: nba-elt-rest-api
        image: 717791819289.dkr.ecr.us-east-1.amazonaws.com/jacobs_repo:nba_elt_rest_api
        ports:
        - containerPort: 8080
        env:
        - name: IP
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: RDS_HOST
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: RDS_USER
        - name: RDS_PW
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: RDS_PW
        - name: RDS_DB
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: RDS_DB
        - name: RDS_SCHEMA
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: RDS_SCHEMA
        - name: ENV_TYPE
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: ENV_TYPE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: API_KEY
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://api.honeycomb.io"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: OTEL_EXPORTER_OTLP_HEADERS
        - name: OTEL_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: rest-api-secrets
              key: OTEL_SERVICE_NAME
      volumes:
      - name: app-data
        emptyDir: {}
