apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: nba-elt-rest-api-deployment
spec:
 selector:
   # Selector for Pods
   app: nba-elt-rest-api
 ports:
   # Port Map
 - port: 8080
   targetPort: 8080
   protocol: TCP
 type: LoadBalancer