FROM python:3.11-slim as base

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_NO_INTERACTION=1

FROM base AS python-deps

COPY docker/install_packages.sh .
COPY pyproject.toml .
COPY poetry.lock .

RUN ./install_packages.sh
RUN pip install poetry
RUN poetry install --with dev --no-root

FROM base AS runtime

COPY --from=python-deps ./.venv ./.venv
ENV PATH="/.venv/bin:$PATH"

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY config.yaml ./config.yaml
COPY src/ ./src/
COPY static/ ./static/
COPY templates/ ./templates/
COPY pyproject.toml ./pyproject.toml

EXPOSE 8080

CMD ["uvicorn", "src.server:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]