version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/docker/postgres_bootstrap.sql:/docker-entrypoint-initdb.d/z99_dump.sql
    networks:
      - api_network

  rest_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: nba_elt_rest_api_local
    environment:
      - IP=postgres
      - RDS_USER=postgres
      - RDS_PW=postgres
      - RDS_DB=postgres
      - RDS_SCHEMA=nba_prod
      - ENV_TYPE=docker_dev
      - API_KEY=bkmSqgcZMzR1JS3ek8gdNGyOrVefyVkK!
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=bababooiee
      - OTEL_SERVICE_NAME=rest-api-dev
      - GMAIL_OAUTH_ID=aaaa
      - GMAIL_OAUTH_CLIENT_SECRET=bbbb
      - GMAIL_OAUTH_REDIRECT_URL=http://localhost:8080/google_auth
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - api_network
    links:
      - postgres:postgres
    volumes:
      - ${PWD}/src/:/home/appuser/src
      - ${PWD}/static/:/home/appuser/static
      - ${PWD}/templates:/home/appuser/templates
      - ${PWD}/config.yaml:/home/appuser/config.yaml
      # these are for fast local docker compose dev so changes will automatically make it into the app

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   volumes:
  #     - .././prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - api_network

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   # volumes:
  #   #   - grafana_data:/var/lib/grafana
  #   networks:
  #     - api_network

# volumes:
#   grafana_data:

networks:
  api_network:
