name: REST API Test Pipeline

on:
  pull_request:

env:
  IP: localhost
  RDS_USER: postgres
  RDS_PW: postgres
  RDS_DB: postgres
  RDS_SCHEMA: nba_prod
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Install Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Cache Python 3.11
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install Dependencies
        env:
          WORKON_HOME: ~/.local/share/virtualenvs
          POETRY_CACHE_DIR: ~/.cache/pypoetry
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: poetry install --with dev --no-root

      - name: Run Tests
        env:
          ENV_TYPE: dev
        run: |
          make test

      - name: Coveralls
        run: |
          poetry run coveralls
